--------------------------------------------------------------------------
--	Crytek Source File.
-- 	Copyright (C), Crytek Studios, 2001-2004.
--------------------------------------------------------------------------
--	$Id$
--	$DateTime$
--	Description: Character SCRIPT for alien outdoors
--  
--------------------------------------------------------------------------
--  History:
--  - 11/12/2004   : Created by Kirill Bulatsev
--  - 05/04/2005   : CXP Rush Clean up by Mikko Mononen
--  - 01/07/2005   : New naming convention.
--	- 29/11/2005   : Revised for new attack patterns by Tetsuji Iwasaki
--------------------------------------------------------------------------

AICharacter.Scout = {

	ScoutIdle = {
		TO_SCOUT_IDLE					= "",
		TO_SCOUT_ATTACK				= "ScoutAttack",
		TO_SCOUT_CIRCLING			= "ScoutCircling",
		TO_SCOUT_PATROL				= "ScoutPatrol",
		TO_SCOUT_HIDE					= "",
		TO_SCOUT_MOARATTACK		= "",
		TO_SCOUT_FLYOVER			= "",
		TO_SCOUT_MELEE				= "",
		TO_SCOUT_GRAB					= "",
		TO_SCOUT_ROUNDATTACK	= "",
		TO_SCOUT_HOVERATTACK	= "",
		TO_SCOUT_PICKATTACK   = "",
		TO_SCOUT_ATTACKVEHICLE= "",
		GO_ENEMY_FOUND				= "ScoutAlert",
	},	
	ScoutAttack = {
		TO_SCOUT_IDLE					= "ScoutIdle",
		TO_SCOUT_ATTACK				= "",
		TO_SCOUT_CIRCLING			= "",
		TO_SCOUT_PATROL				= "ScoutPatrol",
		TO_SCOUT_HIDE					= "ScoutHide",
		TO_SCOUT_MOARATTACK		= "ScoutMOARAttack",
		TO_SCOUT_FLYOVER			= "ScoutFlyOver",
		TO_SCOUT_MELEE				= "ScoutMelee",
		TO_SCOUT_GRAB					= "ScoutGrab",
		TO_SCOUT_ROUNDATTACK	= "ScoutRoundAttack",
		TO_SCOUT_HOVERATTACK	= "ScoutHoverAttack",
		TO_SCOUT_PICKATTACK   = "",
		TO_SCOUT_ATTACKVEHICLE= "ScoutAttackVehicle",
		GO_ENEMY_FOUND				= "",
	},
	ScoutAlert = {
		TO_SCOUT_IDLE					= "ScoutIdle",
		TO_SCOUT_ATTACK				= "ScoutAttack",
		TO_SCOUT_CIRCLING			= "",
		TO_SCOUT_PATROL				= "",
		TO_SCOUT_HIDE					= "",
		TO_SCOUT_MOARATTACK		= "",
		TO_SCOUT_FLYOVER			= "",
		TO_SCOUT_MELEE				= "",
		TO_SCOUT_GRAB					= "",
		TO_SCOUT_ROUNDATTACK	= "",
		TO_SCOUT_HOVERATTACK	= "",
		TO_SCOUT_PICKATTACK   = "",
		TO_SCOUT_ATTACKVEHICLE= "",
		GO_ENEMY_FOUND				= "",
	},
	ScoutCircling = {
		TO_SCOUT_IDLE					= "ScoutIdle",
		TO_SCOUT_ATTACK				= "ScoutAttack",
		TO_SCOUT_CIRCLING			= "",
		TO_SCOUT_PATROL				= "",
		TO_SCOUT_HIDE					= "",
		TO_SCOUT_MOARATTACK		= "",
		TO_SCOUT_FLYOVER			= "",
		TO_SCOUT_MELEE				= "",
		TO_SCOUT_GRAB					= "",
		TO_SCOUT_ROUNDATTACK	= "",
		TO_SCOUT_HOVERATTACK	= "",
		TO_SCOUT_PICKATTACK   = "",
		TO_SCOUT_ATTACKVEHICLE= "",
		GO_ENEMY_FOUND				= "",
	},
	ScoutPatrol = {
		TO_SCOUT_IDLE					= "",
		TO_SCOUT_ATTACK				= "ScoutAttack",
		TO_SCOUT_CIRCLING			= "ScoutCircling",
		TO_SCOUT_PATROL				= "",
		TO_SCOUT_HIDE					= "",
		TO_SCOUT_MOARATTACK		= "",
		TO_SCOUT_FLYOVER			= "",
		TO_SCOUT_MELEE				= "",
		TO_SCOUT_GRAB					= "",
		TO_SCOUT_ROUNDATTACK	= "",
		TO_SCOUT_HOVERATTACK	= "",
		TO_SCOUT_PICKATTACK   = "",
		TO_SCOUT_ATTACKVEHICLE= "",
		GO_ENEMY_FOUND				= "ScoutAlert",
	},
	ScoutHide = {
		TO_SCOUT_IDLE					= "",
		TO_SCOUT_ATTACK				= "ScoutAttack",
		TO_SCOUT_CIRCLING			= "",
		TO_SCOUT_PATROL				= "ScoutPatrol",
		TO_SCOUT_HIDE					= "",
		TO_SCOUT_MOARATTACK		= "",
		TO_SCOUT_FLYOVER			= "",
		TO_SCOUT_MELEE				= "",
		TO_SCOUT_GRAB					= "",
		TO_SCOUT_ROUNDATTACK	= "ScoutRoundAttack",
		TO_SCOUT_HOVERATTACK	= "",
		TO_SCOUT_PICKATTACK   = "",
		TO_SCOUT_ATTACKVEHICLE= "",
		GO_ENEMY_FOUND				= "",
	},
	ScoutMOARAttack = {
		TO_SCOUT_IDLE					= "",
		TO_SCOUT_ATTACK				= "ScoutAttack",
		TO_SCOUT_CIRCLING			= "",
		TO_SCOUT_PATROL				= "",
		TO_SCOUT_HIDE					= "",
		TO_SCOUT_MOARATTACK		= "",
		TO_SCOUT_FLYOVER			= "",
		TO_SCOUT_MELEE				= "",
		TO_SCOUT_GRAB					= "",
		TO_SCOUT_ROUNDATTACK	= "",
		TO_SCOUT_HOVERATTACK	= "",
		TO_SCOUT_PICKATTACK   = "",
		TO_SCOUT_ATTACKVEHICLE= "",
		GO_ENEMY_FOUND				= "",
	},
	ScoutFlyOver = {
		TO_SCOUT_IDLE					= "",
		TO_SCOUT_ATTACK				= "ScoutAttack",
		TO_SCOUT_CIRCLING			= "",
		TO_SCOUT_PATROL				= "",
		TO_SCOUT_HIDE					= "",
		TO_SCOUT_MOARATTACK		= "",
		TO_SCOUT_FLYOVER			= "",
		TO_SCOUT_MELEE				= "",
		TO_SCOUT_GRAB					= "",
		TO_SCOUT_ROUNDATTACK	= "",
		TO_SCOUT_HOVERATTACK	= "",
		TO_SCOUT_PICKATTACK   = "",
		TO_SCOUT_ATTACKVEHICLE= "",
		GO_ENEMY_FOUND				= "",
	},
	ScoutMelee = {
		TO_SCOUT_IDLE					= "",
		TO_SCOUT_ATTACK				= "ScoutAttack",
		TO_SCOUT_CIRCLING			= "",
		TO_SCOUT_PATROL				= "",
		TO_SCOUT_HIDE					= "",
		TO_SCOUT_MOARATTACK		= "",
		TO_SCOUT_FLYOVER			= "",
		TO_SCOUT_MELEE				= "",
		TO_SCOUT_GRAB					= "",
		TO_SCOUT_ROUNDATTACK	= "",
		TO_SCOUT_HOVERATTACK	= "",
		TO_SCOUT_PICKATTACK   = "",
		TO_SCOUT_ATTACKVEHICLE= "",
		GO_ENEMY_FOUND				= "",
	},
	ScoutGrab = {
		TO_SCOUT_IDLE					= "",
		TO_SCOUT_ATTACK				= "ScoutAttack",
		TO_SCOUT_CIRCLING			= "",
		TO_SCOUT_PATROL				= "",
		TO_SCOUT_HIDE					= "",
		TO_SCOUT_MOARATTACK		= "",
		TO_SCOUT_FLYOVER			= "",
		TO_SCOUT_MELEE				= "",
		TO_SCOUT_GRAB					= "",
		TO_SCOUT_ROUNDATTACK	= "",
		TO_SCOUT_HOVERATTACK	= "",
		TO_SCOUT_PICKATTACK   = "",
		TO_SCOUT_ATTACKVEHICLE= "",
		GO_ENEMY_FOUND				= "",
	},
	ScoutRoundAttack = {
		TO_SCOUT_IDLE					= "",
		TO_SCOUT_ATTACK				= "ScoutAttack",
		TO_SCOUT_CIRCLING			= "",
		TO_SCOUT_PATROL				= "",
		TO_SCOUT_HIDE					= "",
		TO_SCOUT_MOARATTACK		= "",
		TO_SCOUT_FLYOVER			= "",
		TO_SCOUT_MELEE				= "",
		TO_SCOUT_GRAB					= "",
		TO_SCOUT_ROUNDATTACK	= "",
		TO_SCOUT_HOVERATTACK	= "",
		TO_SCOUT_PICKATTACK   = "",
		TO_SCOUT_ATTACKVEHICLE= "",
		GO_ENEMY_FOUND				= "",
	},
	ScoutHoverAttack = {
		TO_SCOUT_IDLE					= "",
		TO_SCOUT_ATTACK				= "ScoutAttack",
		TO_SCOUT_CIRCLING			= "",
		TO_SCOUT_PATROL				= "",
		TO_SCOUT_HIDE					= "",
		TO_SCOUT_MOARATTACK		= "",
		TO_SCOUT_FLYOVER			= "ScoutFlyOver",
		TO_SCOUT_MELEE				= "ScoutMelee",
		TO_SCOUT_GRAB					= "ScoutGrab",
		TO_SCOUT_ROUNDATTACK	= "",
		TO_SCOUT_HOVERATTACK	= "",
		TO_SCOUT_PICKATTACK   = "ScoutPickAttack",
		TO_SCOUT_ATTACKVEHICLE= "ScoutAttackVehicle",
		GO_ENEMY_FOUND				= "",
	},
	ScoutPickAttack = {
		TO_SCOUT_IDLE					= "",
		TO_SCOUT_ATTACK				= "ScoutAttack",
		TO_SCOUT_CIRCLING			= "",
		TO_SCOUT_PATROL				= "",
		TO_SCOUT_HIDE					= "",
		TO_SCOUT_MOARATTACK		= "",
		TO_SCOUT_FLYOVER			= "",
		TO_SCOUT_MELEE				= "",
		TO_SCOUT_GRAB					= "",
		TO_SCOUT_ROUNDATTACK	= "",
		TO_SCOUT_HOVERATTACK	= "",
		TO_SCOUT_PICKATTACK   = "",
		TO_SCOUT_ATTACKVEHICLE= "",
		GO_ENEMY_FOUND				= "",
	},
	ScoutAttackVehicle = {
		TO_SCOUT_IDLE					= "",
		TO_SCOUT_ATTACK				= "ScoutAttack",
		TO_SCOUT_CIRCLING			= "",
		TO_SCOUT_PATROL				= "",
		TO_SCOUT_HIDE					= "",
		TO_SCOUT_MOARATTACK		= "",
		TO_SCOUT_FLYOVER			= "",
		TO_SCOUT_MELEE				= "",
		TO_SCOUT_GRAB					= "",
		TO_SCOUT_ROUNDATTACK	= "",
		TO_SCOUT_HOVERATTACK	= "",
		TO_SCOUT_PICKATTACK   = "",
		TO_SCOUT_ATTACKVEHICLE= "",
		GO_ENEMY_FOUND				= "",
	},

	ScoutArchAlienBossFight = {
	},
	
	--[[

	AnyBehavior = {
		GO_DUMB_ATTACK 					= "ScoutDumbAttack",
	},

	ScoutIdle = {
		OnPlayerSeen    				= "ScoutAttack",
		OnEnemyDamage						= "ScoutAttack",
		OnThreateningSoundHeard = "ScoutAttack",
		GO_SEARCH    						= "ScoutSearch",
		GO_PATROL								= "ScoutPatrol",
		GO_ESCORT								= "ScoutEscort",
		GO_ATTACK								= "ScoutAttack",
		GO_SEARCH    						= "ScoutSearch",
	},

	ScoutAttack = {
		OnPlayerSeen    				=	"",
		OnNoHidingPlace 				= "",
		OnNoTarget							= "",
		OnSoreDamage						= "ScoutRecoil",
		GO_ENEMY_LOST						= "ScoutAlert",
		GO_RECOIL								= "ScoutRecoil",
	},

	ScoutEscort = {
		OnNoHidingPlace 				= "",
		OnNoTarget							= "",
		GO_PATROL								= "ScoutPatrol",
		GO_SEARCH    						= "ScoutSearch",
		GO_ABORT_ESCORT					= "ScoutRecoil",
	},

	ScoutExit = {
		GO_SEARCH    						= "ScoutSearch",
		GO_PATROL								= "ScoutPatrol",
		GO_ESCORT								= "ScoutEscort",
	},

	ScoutSearch = {
		OnPlayerSeen    				= "",
		OnEnemyDamage						= "ScoutAttack",
		OnThreateningSoundHeard = "",
		GO_ENEMY_FOUND					= "ScoutAlert",
		GO_PATROL								= "ScoutPatrol",
		GO_ESCORT								= "ScoutEscort",
		GO_ATTACK								= "ScoutAttack",
	},

	ScoutRecoil = {
		OnPlayerSeen    				= "",
		GO_RECOIL_DONE					= "ScoutAttack",
	},

	ScoutPatrol = {
		OnPlayerSeen    				= "",
		OnEnemyDamage						= "ScoutAttack",
		OnThreateningSoundHeard = "ScoutAttack",
		GO_ENEMY_FOUND					= "ScoutAlert",
		GO_ATTACK								= "ScoutAttack",
		GO_SEARCH    						= "ScoutSearch",
		GO_ESCORT								= "ScoutEscort",
	},

	ScoutAlert = {
		OnPlayerSeen    				= "",
		OnEnemyDamage						= "ScoutAttack",
		OnThreateningSoundHeard = "",
		GO_PATROL								= "ScoutPatrol",
		GO_SEARCH    						= "ScoutSearch",
		GO_ESCORT								= "ScoutEscort",
		GO_ATTACK								= "ScoutAttack",
	},
	
	--]]

}
